services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  device-mngt:
    image: device-mngt:latest
    build:
      context: .
      dockerfile: DeviceManagement\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=devices
    ports:
     - 7001:80
    depends_on:
      - postgres

volumes:
  pgdata: